TR-277 JSON skeema kuvaukset englanniksi
FinnishCustoms-SuomenTulli/account-register-information-update pull request #13
Opened 2019-10-11 06:07 UTC by ext-attelaine

2019-10-11 06:31 UTC, ext-alexpeltonen requested changes

2019-10-11 06:31 UTC, ext-alexpeltonen commented on schemas/information_update.json
> +          "description": "If businessId is a Finnish business id (Y-tunnus) businessIdCountryCode value is set to “FI”. If Finnish business id or equivalent is not available, anotherOrganizationId ha
*otherOrganisationId

2019-10-11 06:36 UTC, ext-attelaine commented on schemas/information_update.json
> +          "description": "If businessId is a Finnish business id (Y-tunnus) businessIdCountryCode value is set to “FI”. If Finnish business id or equivalent is not available, anotherOrganizationId ha
fixed

2019-10-18 10:08 UTC, ext-timovakeva approved these changes

2019-10-18 10:14 UTC, merged