TR-544 update JSON schema
FinnishCustoms-SuomenTulli/account-register-information-update pull request #29
Opened 2020-03-06 12:17 UTC by PaavoKaltiainen

Updated JSON schema: corrected required information for organisations

2020-03-06 13:53 UTC, malinenesko submitted a review, later dismissed
Muutetaan kuten oli puhe: lisätään erillinen kenttä yhdistysrekisterinumerolla. Sama validointi kuin businessId:llä oli?

2020-03-27 10:21 UTC, ext-alexpeltonen requested changes

2020-03-27 10:21 UTC, ext-alexpeltonen commented on schemas/information_update.json
> +        "registrationDate",
Nämä linjattiin valinnaisiksi

2020-03-27 10:37 UTC, ext-alexpeltonen approved these changes

2020-03-27 10:37 UTC, merged