TR-201 Päivitysrajapinnan esimerkki JSON
FinnishCustoms-SuomenTulli/account-register-information-update pull request #3
Opened 2019-09-27 07:54 UTC by PaavoKaltiainen

Added example information update json

2019-09-30 05:42 UTC, ext-attelaine approved these changes

2019-09-30 08:53 UTC, ext-attelaine commented
Tässä PR:ssä tehty myös TR-237

2019-09-30 10:12 UTC, ext-timovakeva approved these changes

2019-10-01 08:18 UTC, ext-alexpeltonen requested changes
Eikö esimerkkitiedostoissa olisi mielekästä olla kattavat mutta minimaaliset esimerkit, eli ei ns. ylimääräistä kamaa?

2019-10-01 08:18 UTC, ext-alexpeltonen commented on examples/example.json
> +      "startDate": "2012-10-26",
Tuoko Maija Meikäläinen esimerkkiin lisäarvoa (on samanlainen rakenne kuin Matti Meikäläinen)?

2019-10-01 08:18 UTC, ext-alexpeltonen commented on examples/example.json
> +          "name": "Yritys Oyj",
onko tämä Oyj tarkoituksella ristiriidassa yhdistysrekisterinumeron kanssa?

2019-10-01 08:18 UTC, ext-alexpeltonen commented on examples/example.json
> +                "startDate": "1999-11-10",
tarvitaanko tätä, eikö beneficiaries-rakenne ole havainnollistettu jo yllä customers-rakenteen alla?

2019-10-01 09:07 UTC, PaavoKaltiainen commented on examples/example.json
> +      "startDate": "2012-10-26",
Sen verran tuo että Matti on tilin omistaja ja Maijalla on siihen käyttöoikeus joka varmaan on ihan yleinen käyttötapaus.

2019-10-01 09:10 UTC, PaavoKaltiainen commented on examples/example.json
> +                "startDate": "1999-11-10",
No eikös oikeushenkilöille pidä aina ilmoittaa edunsaajat?

2019-10-01 09:12 UTC, PaavoKaltiainen commented on examples/example.json
> +          "name": "Yritys Oyj",
Muutetaan sille jokin kuvaavampi nimi.

2019-10-01 10:50 UTC, ext-alexpeltonen commented on examples/example.json
> +      "startDate": "2012-10-26",
Niinpä onkin!

2019-10-01 10:57 UTC, ext-alexpeltonen commented on examples/example.json
> +                "startDate": "1999-11-10",
Totta, katsoin huolimattomasti.

2019-10-01 10:58 UTC, ext-alexpeltonen approved these changes

2019-10-01 10:58 UTC, merged