TR-751: Added minItems:1 for account and safetydepositbox roles
FinnishCustoms-SuomenTulli/account-register-information-update pull request #42
Opened 2020-06-05 06:33 UTC by extMalinEsk

2020-06-05 07:18 UTC, ext-attelaine approved these changes

2020-06-05 07:25 UTC, ext-alexpeltonen requested changes
Version history needs update

2020-06-05 10:23 UTC, extMalinEsk commented
> Version history needs update

Päivitetty.

2020-06-05 10:32 UTC, PaavoKaltiainen approved these changes

2020-06-08 06:47 UTC, ext-attelaine commented on index.md
> +1.0.8|5.6.2020|Lisätty skeemaan tilin ja talletuslokeron roolien vähimmäismääräksi 1.|
Dokumentin alussa oleva versiotieto päivittämättä

2020-06-08 08:39 UTC, extMalinEsk commented on index.md
> +1.0.8|5.6.2020|Lisätty skeemaan tilin ja talletuslokeron roolien vähimmäismääräksi 1.|
Korjattu.

2020-06-08 12:21 UTC, merged